version: '3.5'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3009:3009
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
    tty: true
